"""System-level modules."""

from .audio import AudioManager
from .aim_assist import AimAssistConfig, AimAssistSystem, AimAssistTarget
from .background import BackgroundRenderer
from .character_passives import (
    CHARACTER_PASSIVE_PROFILES,
    DEFAULT_CHARACTER_PASSIVE_ID,
    CharacterPassiveProfile,
    get_character_passive,
)
from .character_supers import (
    CHARACTER_SUPER_PROFILES,
    DEFAULT_CHARACTER_SUPER_ID,
    CharacterSuperProfile,
    get_character_super,
)
from .character_unlocks import (
    BUNNY_UNLOCK_REQUIRED_RUNS,
    CAT_UNLOCK_REQUIRED_HIGH_SCORE,
    CHARACTER_UNLOCK_CONDITIONS,
    CharacterUnlockCondition,
    RACCOON_UNLOCK_REQUIRED_BOSSES,
    UnlockProgressSnapshot,
    evaluate_unlock_progress,
    get_character_unlock_condition,
    get_unlock_condition_by_id,
    is_character_unlocked,
    is_unlock_condition_met,
    list_character_unlock_conditions,
    refresh_meta_unlock_state,
    unlock_thresholds_snapshot,
)
from .game_session import GameSession
from .high_score import load_high_score, save_high_score
from .input_controller import InputController, InputMethod
from .meta_progression import (
    DEFAULT_UNLOCKED_CHARACTERS,
    META_PROGRESSION_FILE_NAME,
    MetaProgression,
    load_meta_progression,
    save_meta_progression,
)
from .paths import asset_path, assets_dir, project_root, runtime_root, saves_dir
from .party_animals import (
    DEFAULT_PARTY_ANIMAL_ID,
    FUTURE_PARTY_ANIMAL_PLACEHOLDERS,
    PLAYABLE_PARTY_ANIMAL_IDS,
    PARTY_ANIMAL_CONFIGS,
    PARTY_ANIMAL_CONFIGS_BY_ID,
    PartyAnimalVisualConfig,
    SHARED_PARTY_ACCESSORY_RULES,
    draw_party_animal_shape,
    get_party_animal,
    list_party_animals,
    register_party_animal,
)
from .player_visual import PlayerRenderer
from .player_visual_anchors import (
    DEFAULT_PLAYER_WEAPON_ANCHOR,
    PLAYER_VISUAL_ANCHORS,
    PlayerVisualAnchorDefinition,
    get_player_visual_anchor,
    list_player_visual_anchors,
    player_render_anchor,
    resolve_player_visual_anchor,
)
from .player_animation import (
    CHARACTER_ANIMATION_CONFIGS,
    DEFAULT_CHARACTER_ANIMATION_ID,
    AnimationClipConfig,
    CharacterAnimationConfig,
    LoadedAnimationClip,
    LoadedCharacterAnimation,
    PlayerAnimationSystem,
    get_character_animation_config,
    load_character_animation,
    list_character_animation_configs,
    register_character_animation_config,
)
from .player_variants import PLAYER_VARIANTS, PLAYER_VARIANTS_BY_ID, PlayerVisualVariant
from .run_progression import RunProgression
from .run_upgrades import RunUpgradeSystem, UpgradeDefinition
from .settings import (
    MAX_START_LEVEL,
    MIN_START_LEVEL,
    RuntimeSettings,
    clamp_selected_start_level,
    load_settings,
    save_settings,
)
from .spawn_controller import SpawnController
from .teddy_shape_variants import TEDDY_SHAPE_VARIANTS, TeddyShapeVariant, draw_teddy_shape_variant
from .ui import UiRenderer
from .visual_feedback import VisualFeedback
from .weapons import (
    DEFAULT_WEAPON_ID,
    WEAPON_DEFINITIONS,
    WEAPON_TYPE_MELEE,
    WEAPON_TYPE_PROJECTILE,
    SparklerAttackProfile,
    WeaponDefinition,
    get_weapon_definition,
    list_weapon_definitions,
)
from .weapon_evolutions import (
    WEAPON_EVOLUTION_DEFINITIONS,
    WeaponEvolutionDefinition,
    WeaponEvolutionTracker,
    eligible_weapon_evolutions,
    get_weapon_evolution,
    list_weapon_evolutions,
)
from .weapon_visual_overlays import (
    DEFAULT_WEAPON_VISUAL_OVERLAY_OWNER,
    WeaponVisualOverlay,
    WeaponVisualOverlayOwner,
)
from .weapon_visual_assets import (
    WEAPON_VISUAL_ASSETS,
    WeaponVisualAssetDefinition,
    get_weapon_visual_asset,
    list_weapon_visual_assets,
    load_weapon_visual_asset,
)
from .weapon_visual_overlay_renderer import WeaponVisualOverlayRenderer
from .weapon_visuals import (
    WeaponVisualAnimationProfile,
    WEAPON_VISUAL_VARIANTS,
    WEAPON_VISUAL_VARIANT_RULES,
    WeaponVisualRotationRule,
    WeaponVisualVariantDefinition,
    WeaponVisualVariantRule,
    get_weapon_visual_variant,
    list_weapon_visual_variants,
    resolve_weapon_visual_variant_id,
    weapon_ids_with_visuals,
)

__all__ = [
    "AudioManager",
    "AimAssistConfig",
    "AimAssistSystem",
    "AimAssistTarget",
    "BackgroundRenderer",
    "CharacterPassiveProfile",
    "CHARACTER_PASSIVE_PROFILES",
    "DEFAULT_CHARACTER_PASSIVE_ID",
    "get_character_passive",
    "CharacterSuperProfile",
    "CHARACTER_SUPER_PROFILES",
    "DEFAULT_CHARACTER_SUPER_ID",
    "get_character_super",
    "CharacterUnlockCondition",
    "BUNNY_UNLOCK_REQUIRED_RUNS",
    "CAT_UNLOCK_REQUIRED_HIGH_SCORE",
    "RACCOON_UNLOCK_REQUIRED_BOSSES",
    "UnlockProgressSnapshot",
    "CHARACTER_UNLOCK_CONDITIONS",
    "list_character_unlock_conditions",
    "get_character_unlock_condition",
    "get_unlock_condition_by_id",
    "is_character_unlocked",
    "is_unlock_condition_met",
    "evaluate_unlock_progress",
    "refresh_meta_unlock_state",
    "unlock_thresholds_snapshot",
    "GameSession",
    "InputController",
    "InputMethod",
    "MetaProgression",
    "META_PROGRESSION_FILE_NAME",
    "DEFAULT_UNLOCKED_CHARACTERS",
    "load_meta_progression",
    "save_meta_progression",
    "SpawnController",
    "PartyAnimalVisualConfig",
    "PARTY_ANIMAL_CONFIGS",
    "PARTY_ANIMAL_CONFIGS_BY_ID",
    "DEFAULT_PARTY_ANIMAL_ID",
    "SHARED_PARTY_ACCESSORY_RULES",
    "FUTURE_PARTY_ANIMAL_PLACEHOLDERS",
    "PLAYABLE_PARTY_ANIMAL_IDS",
    "register_party_animal",
    "list_party_animals",
    "get_party_animal",
    "draw_party_animal_shape",
    "TeddyShapeVariant",
    "TEDDY_SHAPE_VARIANTS",
    "draw_teddy_shape_variant",
    "RuntimeSettings",
    "PlayerRenderer",
    "PlayerVisualAnchorDefinition",
    "PLAYER_VISUAL_ANCHORS",
    "DEFAULT_PLAYER_WEAPON_ANCHOR",
    "get_player_visual_anchor",
    "list_player_visual_anchors",
    "player_render_anchor",
    "resolve_player_visual_anchor",
    "AnimationClipConfig",
    "CharacterAnimationConfig",
    "LoadedAnimationClip",
    "LoadedCharacterAnimation",
    "PlayerAnimationSystem",
    "CHARACTER_ANIMATION_CONFIGS",
    "DEFAULT_CHARACTER_ANIMATION_ID",
    "register_character_animation_config",
    "get_character_animation_config",
    "list_character_animation_configs",
    "load_character_animation",
    "PlayerVisualVariant",
    "PLAYER_VARIANTS",
    "PLAYER_VARIANTS_BY_ID",
    "clamp_selected_start_level",
    "MIN_START_LEVEL",
    "MAX_START_LEVEL",
    "load_settings",
    "save_settings",
    "UiRenderer",
    "VisualFeedback",
    "load_high_score",
    "save_high_score",
    "asset_path",
    "assets_dir",
    "project_root",
    "runtime_root",
    "saves_dir",
    "RunProgression",
    "RunUpgradeSystem",
    "UpgradeDefinition",
    "WeaponDefinition",
    "SparklerAttackProfile",
    "WEAPON_TYPE_PROJECTILE",
    "WEAPON_TYPE_MELEE",
    "WEAPON_DEFINITIONS",
    "DEFAULT_WEAPON_ID",
    "get_weapon_definition",
    "list_weapon_definitions",
    "WeaponEvolutionDefinition",
    "WeaponEvolutionTracker",
    "WEAPON_EVOLUTION_DEFINITIONS",
    "list_weapon_evolutions",
    "get_weapon_evolution",
    "eligible_weapon_evolutions",
    "WeaponVisualOverlay",
    "WeaponVisualOverlayOwner",
    "DEFAULT_WEAPON_VISUAL_OVERLAY_OWNER",
    "WeaponVisualAssetDefinition",
    "WEAPON_VISUAL_ASSETS",
    "get_weapon_visual_asset",
    "list_weapon_visual_assets",
    "load_weapon_visual_asset",
    "WeaponVisualOverlayRenderer",
    "WeaponVisualAnimationProfile",
    "WeaponVisualRotationRule",
    "WeaponVisualVariantDefinition",
    "WeaponVisualVariantRule",
    "WEAPON_VISUAL_VARIANTS",
    "WEAPON_VISUAL_VARIANT_RULES",
    "get_weapon_visual_variant",
    "list_weapon_visual_variants",
    "resolve_weapon_visual_variant_id",
    "weapon_ids_with_visuals",
]
